# Generated by Django 4.1 on 2022-08-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_account_comment_post_delete_suggestion_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='home_num',
            field=models.IntegerField(max_length=10),
        ),
    ]
