# Generated by Django 4.1 on 2022-08-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_account_home_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='check_password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='home_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
    ]
