# Generated by Django 4.1 on 2022-08-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_account_check_password_alter_account_home_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='peoNum',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='shopName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='useTime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
